update job

diff --git a/jobscript b/jobscript
--- a/jobscript
+++ b/jobscript
@@ -2,13 +2,19 @@
 #$ -cwd
 #$ -l nvidia_v100    # 使用V100 GPU
 
-# 定义要测试的数据集列表
-dataset_list=("wikipedia" "mooc" "uci" "socialevolve_2weeks")
+# 定义要测试的数据集列表和对应的完整名称
+declare -A dataset_map=(
+    ["wikipedia"]="wikipedia"
+    ["mooc"]="mooc"
+    ["uci"]="uci"
+    ["social"]="socialevolve_2weeks"
+    ["socialevolve_2weeks"]="socialevolve_2weeks"
+)
 
 # 显示使用说明的函数
 usage() {
     printf "Usage: %s <dataset>\n" "$0" >&2
-    printf "Dataset options: wikipedia, mooc, uci, socialevolve_2weeks\n" >&2
+    printf "Dataset options: wikipedia, mooc, uci, social (or socialevolve_2weeks)\n" >&2
     exit 1
 }
 
@@ -17,20 +23,13 @@ if [ $# -lt 1 ]; then
     usage
 fi
 
-# 验证输入的数据集
-dataset=$1
+# 验证输入的数据集并获取完整名称
+input_dataset=$1
+dataset=${dataset_map[$input_dataset]}
 
 # 验证数据集名称
-valid_dataset=0
-for d in "${dataset_list[@]}"; do
-    if [ "$dataset" == "$d" ]; then
-        valid_dataset=1
-        break
-    fi
-done
-
-if [ $valid_dataset -eq 0 ]; then
-    printf "Error: Invalid dataset name. Use one of: wikipedia, mooc, uci, socialevolve_2weeks\n" >&2
+if [ -z "$dataset" ]; then
+    printf "Error: Invalid dataset name. Use one of: wikipedia, mooc, uci, social (or socialevolve_2weeks)\n" >&2
     exit 1
 fi
 
@@ -68,7 +67,7 @@ run_evaluation() {
 conda activate twgsl
 
 # 将文件复制到GPU节点的本地存储
-cp -r ~/papers/FreeDyG/ $TMPDIR
+cp -r ~/scratch/FreeDyG/ $TMPDIR
 
 # 切换到工作目录
 cd $TMPDIR/FreeDyG/
@@ -90,7 +89,7 @@ fi
 rsync -av --progress \
     --exclude 'jobscript.e*' \
     --exclude 'jobscript.o*' \
-    "$TMPDIR/FreeDyG/" ~/papers/FreeDyG/
+    "$TMPDIR/FreeDyG/" ~/scratch/FreeDyG/
 
 # 休眠几秒确保文件同步
 sleep 3
